### PR TITLE
Fix issue, minor adjustments

### PR DESCRIPTION
**Pull request by calebergh**
My apologies, I know the diff looks like a lot of changes.  In the PHP file, it's limited changes (just removed the dependencies for axios and qs) - but my IDE formatted the file.  The javascript file contains the majority of the changes.

### CODE REVIEW

**Comment by robmarshall** [comment]
Nice one for getting this into a PR. 

Could you do me a favour and remove the formatting. if it is only small changes - I would recommend copying them out, reverting to the original fork, then readd without this extra formatting.

Otherwise I am unable to confirm what you have changed.

**Comment by calebergh** [comment]
Yes, will do.  I understand.  Give me a bit of time, and I'll get it 
updated.

**Comment by calebergh** [comment]
Hi Robert - I've removed the noisy formatting.  The javascript file is 
heavily modified, so it still shows a lot of changes.

**Comment by robmarshall** [comment]
Hi @calebergh What is the reason for introducing jQuery? I would like to avoid the use of that package, and it doesn't make sense to me to introduce just to correct a dash issue.

If your reasoning is because Axios is too heavy when jQuery can do the same thing, I would suggest updating to use fetch instead. The same argument could be made for the QS script as well, this could be updated to use vanilla JS. 

Either way, please remove jQuery and lets get this fix in :)

**Comment by calebergh** [comment]
This doesn't introduce jQuery.  Gravity Forms already uses / loads jQuery, so we're just leveraging an existing library that is shipped with WP, and guaranteed to be loaded in this case due to Gravity Forms.

**Comment by calebergh** [comment]
Also @robmarshall  - this isn't purely a dash issue.  When multiple forms are on a page, the script is incorrectly using the form ID from the _last_ form, even when the submission was on an earlier form.  The use of jQuery here allows for simpler DOM navigation on the submit event to get the proper form ID, which was the ACTUAL solution to my problem, but while I was in there, I opted to add the regex replace to ensure the problem was solved in other cases as well (I don't see GF introducing invalid characters into form IDs, but I also felt it was valid / important to sanitize the form ID to be sure this didn't come up again in the future).

**Comment by robmarshall** [comment]
Thanks for explaining the ID bug. I missed that! :)

In regards to jQuery, I would like it to not be used in this plugin. The required functionality is easy enough to reproduce using vanilla JS.

**Comment by calebergh** [comment]
Hi Robert:

I appreciate your position, but I'm unwilling to spend the time to 
refactor this yet again to pull out jQuery.  Feel free to use any of the 
work I've done if you want to take that on yourself.

Best,

Cale

**Comment by robmarshall** [comment]
That it completely understandable. Thanks for your time in highlighting this issue.

**Pull request closed without merging**
